import { migrateToLanguageField } from 'sanity-plugin-internationalized-array/migrations'

const DOCUMENT_TYPES = [
	'site',
	'page',
	'blog.post',
	'blog.category',
	'navigation',
	'homepage',
	'announcement',
	'redirect',
	'logo',
	'theme',
	'person',
	'pricing',
	'reputation',
	'testimonial',
	'event',
	'fabrique',
	'lefestival',
	'festival',
	'bigbangShortStory',
	'bigbangLongStory',
	'memoire',
	'film',
	'photo',
	'video',
	'genre',
	'jury',
	'callForParticipation',
	'programming',
	'award',
	'practicalInfo',
	'press',
	'contact',
	'filmSubmission',
]

export default migrateToLanguageField(DOCUMENT_TYPES)
